config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get  'about' => 'pages#about'
  get  'contacts' => 'pages#contacts'
  get  'luogo' => 'pages#luogo'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about	
  end
  def contacts
  end
  def luogo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer #546e7a blue-grey darken-1">
 <div class="footer-copyright">
    <div class="container left">
      ©lnovizio
      <a class="grey-text text-lighten-4 right" href="#1">Altro da novicar</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed">	
	<nav class= "#1a237e indigo darken-4">
		<div class="row nav-wrapper">
			<div class="col s1 center"><%=link_to"Novicar snc", root_path, class: "brand-logo"%></div>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
			<li><%=link_to "Come contattarci?", contacts_path %></li>
			<li><%=link_to "Vieni a trovarci", luogo_path%></li>
			<li><%=link_to "Scopri di più", about_path %></li>
			</ul>
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Novicar</title>
		<%= csrf_meta_tags %>
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	<body> 
		<%= render "layouts/header"%>
		<main>
		<%= yield %>
		</main>
		<%= render "layouts/footer"%>
	
	</body>
</html>

app/views/pages/about.html.erb
<h1>Chi siamo</h1>
<p>Siamo un agenzia di pratiche auto/moto situata nei paesi vesuviani</p>

app/views/pages/contacts.html.erb
<div class="row center">
	<h1>Come contattarci?</h1>
	<div class="col s6">	
		<h3>E-mail</h3>						
		<p>novicarsnc@gmail.com</p>
	</div>
	<div class="col s6">
		<h3>Telefono</h3>
		<p>0815301683</p>
	</div>	
	<div class="col s12">
		<h2>Oppure</h2>
		<a class="btn #1a237e indigo darken-4" href="luogo">Vieni a trovarci</a>
	</div>
</div>

app/views/pages/home.html.erb
<h1 class="center"> Hai intenzione di comprare un veicolo?</h1>
<h2 class="center"> Hai pensato dove effettuare il passaggio?</h2>
<h3 class="center"> Vieni a trovarci!</h3>



<h3 class="center">Ti offriamo:</h3>

app/views/pages/luogo.html.erb
<div class= "center">
	<h1>Dove trovarci?</h1>
	<font face= "Verdana" size="5"><p>Vieni a trovarci in:</p>
	<p>Via Madonna Dell'Arco 563, Sant'Anastasia (NA)</p></font>
</div>